Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,16 @@ jobs:
         continue-on-error: true
         run: |
            ng add @angular-eslint/schematics --skip-confirmation
-           ng lint  
+           ng lint > log.txt 2>&1; echo $?
+           cat $GITHUB_WORKSPACE/log.txt | grep "linting" >> $GITHUB_WORKSPACE/errors.txt
+      - name: Generate HTML Summary
+        if: always()
+        run: |
+          echo "<html><body><pre>" > $GITHUB_WORKSPACE/summary.html
+          cat $GITHUB_WORKSPACE/errors.txt >> $GITHUB_WORKSPACE/summary.html
+          echo "</pre></body></html>" >> $GITHUB_WORKSPACE/summary.html
+          cat $GITHUB_WORKSPACE/summary.html >> $GITHUB_STEP_SUMMARY
+           
       - name: test
         run: |
           ng test --watch=false --browsers=ChromeHeadless 
